name: json_config_generator
description: Configuration generator from json files.
version: 0.1.3
homepage: https://github.com/deCardenas/json_config_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  dart_style: ^2.3.3
  source_gen: ^1.4.0
  code_builder: ^4.7.0
  build_config: ^1.1.1
  built_collection: ^5.1.1
  json_config_annotation: ^0.1.1
  recase: ^4.1.0

dev_dependencies:
